<a href="https://colab.research.google.com/github/benasphy/Linear-Regression/blob/main/NormalEq_Vs_PseudoInverse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- **Normal Equation**

In [18]:
import numpy as np
import pandas as pd

In [54]:
class Linear_Reg_NormalEq:
  def __init__(self):
    self.theta = None

  def fit(self, X, y):
    X = np.array(X)
    y = np.array(y).reshape(-1, 1)

    X_b = np.c_[np.ones((X.shape[0], 1)), X]
    self.theta = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

  def predict(self, X):
    X = np.array(X)
    X_b = np.c_[np.ones((X.shape[0], 1)), X]
    return np.dot(X_b, self.theta)

  def evaluate(self, X, y):
    y_pred = self.predict(X)
    y = np.array(y).reshape(-1, 1)
    mse = np.mean((y - y_pred) ** 2)
    return mse



In [55]:
data = {
    'X': [1, 2, 3, 4, 5],
    'y': [2, 4, 5, 4, 5]
}
df = pd.DataFrame(data)

X = df[['X']]
y = df['y']

In [56]:
model = Linear_Reg_NormalEq()
model.fit(X, y)

In [57]:
print(model.theta)

[[2.2]
 [0.6]]


In [58]:
predictions = model.predict(X)
predictions

array([[2.8],
       [3.4],
       [4. ],
       [4.6],
       [5.2]])

In [59]:
mse = model.evaluate(X, y)
print(mse)

0.47999999999999987


- **Moore-Penrose PseudoInverse**

In [61]:
class Linear_Reg_PseudoInv:
  def __init__(self):
    self.theta = None

  def fit(self, X, y):
    X = np.array(X)
    y = np.array(y).reshape(-1, 1)

    X_b = np.c_[np.ones((X.shape[0], 1)), X]
    self.theta = np.linalg.pinv(X_b).dot(y)

  def predict(self, X):
    X = np.array(X)
    X_b = np.c_[np.ones((X.shape[0], 1)), X]
    return np.dot(X_b, self.theta)

  def evaluate(self, X, y):
    y_pred = self.predict(X)
    y = np.array(y).reshape(-1, 1)
    mse = np.mean((y - y_pred) ** 2)
    return mse



In [62]:
data = {
    'X': [1, 2, 3, 4, 5],
    'y': [2, 4, 5, 4, 5]
}
df = pd.DataFrame(data)

X = df[['X']]
y = df['y']

In [63]:
model = Linear_Reg_PseudoInv()
model.fit(X, y)

In [64]:
print(model.theta)

[[2.2]
 [0.6]]
